/* ============================================================
   DROP ALL — EQUIPO65
   Wipes the entire schema: triggers, procedure, and all tables.
   Safe to run even if the schema is partially initialised —
   each statement is wrapped so missing objects are silently skipped.

   After running this file, re-initialise with the 8 steps in
   mds/DB_SETUP_GUIDE.md.
   ============================================================ */


/* ============================================================
   1. DROP TRIGGERS
   ============================================================ */
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_TAREAS_COMPLETADAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_CUMPLIMIENTO';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_REABIERTAS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_ACTUALIZACION_DIA';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_TRAZABILIDAD';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_DESPLIEGUES_PROD';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_MTTR';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_TASA_EXITO';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_BOT';                 EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_DISPONIBILIDAD';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_KPI_INCIDENTES_SEG';      EXCEPTION WHEN OTHERS THEN NULL; END;
/


/* ============================================================
   2. DROP PROCEDURE
   ============================================================ */
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE UPSERT_KPI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


/* ============================================================
   3. DROP TABLES
   Reverse FK dependency order.
   CASCADE CONSTRAINTS drops any remaining FK references automatically.
   PURGE skips the recycle bin so identity sequences reset cleanly.
   ============================================================ */

-- Leaf tables (no other table references them)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AUDIT_LOG          CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BOT_INTERACTIONS   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LLM_ANALYSIS       CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE KPI_VALUES         CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE KPI_TYPES          CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE INCIDENTS          CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEPLOYMENTS        CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TASK_SPRINT_HISTORY CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TASK_STATUS_HISTORY CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TASKS references PROJECTS, SPRINTS, USERS (and itself via PARENT_TASK_ID)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TASKS              CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Junction tables
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROJECT_SPRINTS    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROJECT_MEMBERS    CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- PROJECTS references USERS (MANAGER_ID)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROJECTS           CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SPRINTS            CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USER_CREDENTIALS   CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- USERS references ROLES and TEAMS
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USERS              CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEAMS              CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ROLES              CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


/* ============================================================
   4. VERIFY — should return 0 rows for each
   ============================================================ */
SELECT OBJECT_NAME, OBJECT_TYPE
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('TABLE','TRIGGER','PROCEDURE')
ORDER BY OBJECT_TYPE, OBJECT_NAME;
