-- ============================================================
-- SPRINT 2
-- ============================================================
INSERT INTO SPRINTS (SPRINT_ID, NAME, START_DATE, END_DATE, STATUS, TOTAL_HOURS, CREATED_AT, IS_DELETED)
VALUES (2, 'Sprint 2 - Bot de Telegram y Operaciones de Tareas', DATE '2026-04-01', DATE '2026-04-15', 'CLOSED', 27, TIMESTAMP '2026-04-01 00:00:00', 'N');

INSERT INTO PROJECT_SPRINTS (PROJECT_ID, SPRINT_ID, SPRINT_NUMBER, IS_ACTIVE, ASSIGNED_AT)
VALUES (1, 2, 2, 'N', TIMESTAMP '2026-04-01 00:00:00');

-- ============================================================
-- SPRINT 2 TASKS
-- ============================================================
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Comando /start', 'Implementar comando /start — captura telegram_id y username del usuario', 'COMPLETED', 'DONE', 'HIGH', 6, 1, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Lógica validación usuario', 'Lógica de validación: usuario existente -> bienvenida; nuevo -> registro', 'COMPLETED', 'DONE', 'HIGH', 6, 4, DATE '2026-04-15', 3, 3, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Confirmación de registro', 'Confirmar registro con respuesta del bot (mensaje con datos guardados)', 'COMPLETED', 'DONE', 'MEDIUM', 1, 2, DATE '2026-04-15', 1, 1, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Comando /addtask', 'Implementar comando /addtask con parámetros: titulo, descripcion, horas_estimadas, prioridad', 'COMPLETED', 'DONE', 'HIGH', 6, 1, DATE '2026-04-15', 3, 3, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Validación horas estimadas', 'Validación: si horas_estimadas > 4 el bot rechaza y solicita subdividir la tarea', 'COMPLETED', 'DONE', 'MEDIUM', 6, 4, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Asignación por telegram_id', 'Asignar developer_id automáticamente por telegram_id del usuario que envía el comando', 'COMPLETED', 'DONE', 'MEDIUM', 1, 2, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Comando /assigntask', 'Implementar comando /assigntask con parámetro: task_id', 'COMPLETED', 'DONE', 'HIGH', 6, 1, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Detección sprint activo', 'Obtener automáticamente el sprint con status = ACTIVE para asignación', 'COMPLETED', 'DONE', 'MEDIUM', 6, 4, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'UPDATE tarea a IN_PROGRESS', 'UPDATE en TASKS: status a IN_PROGRESS, sprint_id asignado, fecha_inicio = SYSDATE', 'COMPLETED', 'DONE', 'MEDIUM', 1, 2, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Comando /completetask', 'Implementar comando /completetask con parámetros: task_id, horas_reales, comentario (opcional)', 'COMPLETED', 'DONE', 'HIGH', 6, 1, DATE '2026-04-15', 3, 3, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Validación propietario tarea', 'Validar que el developer que ejecuta el comando sea el propietario de la tarea', 'COMPLETED', 'DONE', 'MEDIUM', 6, 4, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'UPDATE tarea a COMPLETED', 'UPDATE en TASKS: status a COMPLETED, horas_reales, fecha_fin = SYSDATE, comentario', 'COMPLETED', 'DONE', 'MEDIUM', 1, 2, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Cálculo de varianza', 'Calcular y almacenar varianza = horas_reales - horas_estimadas (campo en TASKS)', 'COMPLETED', 'DONE', 'MEDIUM', 1, 4, DATE '2026-04-15', 1, 1, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Comando /kpi', 'Implementar comando /kpi: tareas completadas, horas estimadas vs reales, varianza promedio por developer', 'COMPLETED', 'DONE', 'HIGH', 6, 3, DATE '2026-04-15', 4, 4, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'KPI por developer', 'Mostrar KPI por developer (% cumplimiento, total horas invertidas)', 'COMPLETED', 'DONE', 'MEDIUM', 6, 5, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Evidencia SQL KPI', 'Mostrar evidencia SQL del query KPI ejecutado directamente en ATP', 'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2026-04-15', 1, 1, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Verificar IP pública', 'Verificar y documentar IP pública del servidor (debe iniciar con 140.)', 'COMPLETED', 'DONE', 'MEDIUM', 6, 6, DATE '2026-04-15', 1, 1, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Demo bot conectado a ATP', 'Demostrar que el bot de Telegram funciona conectado a la BD ATP actualizada', 'COMPLETED', 'DONE', 'HIGH', 6, 6, DATE '2026-04-15', 1, 1, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Cambios en Cloud BD con SQL', 'Mostrar cambios en la Cloud BD con SQL en cada operación (add, assign, complete)', 'COMPLETED', 'DONE', 'MEDIUM', 1, 6, DATE '2026-04-15', 2, 2, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 2, 'Alta de tasks en Oracle Bot', 'Dar de alta TODAS las tasks del sprint en el Oracle Bot antes de iniciar trabajo', 'COMPLETED', 'DONE', 'HIGH', 1, 6, DATE '2026-04-15', 1, 1, 'N', NULL, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

COMMIT;
