-- ============================================================
-- PROJECT
-- ============================================================
INSERT INTO PROJECTS (PROJECT_ID, NAME, DESCRIPTION, MANAGER_ID, STATUS, TOTAL_HOURS, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 'OCI Task Manager', 'Sistema de gestión de tareas, sprints y KPIs para el equipo de desarrollo Oracle OCI', 1, 'ACTIVE', 109, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-04-27 00:00:00', 'N');

-- ============================================================
-- PROJECT MEMBERS
-- ============================================================
INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT, JOINED_AT, IS_DELETED)
VALUES (1, 1, 'MANAGER', TIMESTAMP '2026-02-11 00:00:00', 'N');

INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT, JOINED_AT, IS_DELETED)
VALUES (1, 2, 'DEVELOPER', TIMESTAMP '2026-02-11 00:00:00', 'N');

INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT, JOINED_AT, IS_DELETED)
VALUES (1, 3, 'DEVELOPER', TIMESTAMP '2026-02-11 00:00:00', 'N');

INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT, JOINED_AT, IS_DELETED)
VALUES (1, 4, 'DEVELOPER', TIMESTAMP '2026-02-11 00:00:00', 'N');

INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT, JOINED_AT, IS_DELETED)
VALUES (1, 5, 'DEVELOPER', TIMESTAMP '2026-02-11 00:00:00', 'N');

INSERT INTO PROJECT_MEMBERS (PROJECT_ID, USER_ID, ROLE_IN_PROJECT, JOINED_AT, IS_DELETED)
VALUES (1, 6, 'SCRUM_MASTER', TIMESTAMP '2026-02-11 00:00:00', 'N');

-- ============================================================
-- SPRINT 1
-- ============================================================
INSERT INTO SPRINTS (SPRINT_ID, NAME, START_DATE, END_DATE, STATUS, TOTAL_HOURS, CREATED_AT, IS_DELETED)
VALUES (1, 'Sprint 1 - Plan, Requerimientos y Documentación Base', DATE '2026-02-11', DATE '2026-02-25', 'CLOSED', 35, TIMESTAMP '2026-02-11 00:00:00', 'N');

INSERT INTO PROJECT_SPRINTS (PROJECT_ID, SPRINT_ID, SPRINT_NUMBER, IS_ACTIVE, ASSIGNED_AT)
VALUES (1, 1, 1, 'N', TIMESTAMP '2026-02-11 00:00:00');

-- ============================================================
-- SPRINT 1 TASKS
-- ============================================================
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Visión y alcance del proyecto', 'Redactar visión y alcance del proyecto (propósito y resultado esperado)', 'COMPLETED', 'DONE', 'MEDIUM', 6, 1, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Objetivos y entregables de alto nivel', 'Definir objetivos y entregables de alto nivel; indicar qué está dentro y fuera del alcance', 'COMPLETED', 'DONE', 'MEDIUM', 6, 2, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Impacto económico inicial', 'Calcular impacto económico inicial (puede adelantarse desde punto 7)', 'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Objetivo del Sprint 1', 'Establecer objetivo del Sprint 1 con metas y entregables específicos', 'COMPLETED', 'DONE', 'MEDIUM', 1, 4, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Sprint Backlog priorizado', 'Construir Sprint Backlog priorizando tareas del product backlog', 'COMPLETED', 'DONE', 'MEDIUM', 6, 5, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Capacidad del equipo', 'Estimar capacidad del equipo para asegurar carga de trabajo realista', 'COMPLETED', 'DONE', 'MEDIUM', 6, 6, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Cronograma e hitos', 'Definir cronograma con línea de tiempo e hitos clave', 'COMPLETED', 'DONE', 'MEDIUM', 1, 1, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Requerimientos funcionales', 'Levantar y numerar todos los requerimientos funcionales', 'COMPLETED', 'DONE', 'MEDIUM', 6, 2, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Verificación de FRs', 'Verificar que cada FR sea claro, no ambiguo, verificable y trazable', 'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Requerimientos no funcionales', 'Levantar y numerar todos los requerimientos no funcionales', 'COMPLETED', 'DONE', 'MEDIUM', 1, 4, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'NFR Oracle', 'Incluir todos los NFR solicitados por Oracle', 'COMPLETED', 'DONE', 'MEDIUM', 6, 5, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Verificación de NFRs', 'Verificar que cada NFR sea claro, no ambiguo, verificable y trazable', 'COMPLETED', 'DONE', 'MEDIUM', 6, 6, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Historias de usuario', 'Redactar una historia de usuario por diapositiva', 'COMPLETED', 'DONE', 'MEDIUM', 1, 1, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Top 3 historias de usuario', 'Seleccionar las 3 historias de usuario de mayor prioridad', 'COMPLETED', 'DONE', 'MEDIUM', 6, 2, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Criterios de aceptación HU', 'Agregar criterios de aceptación a cada historia de usuario seleccionada', 'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Propuesta KPI productividad', 'Elaborar propuesta de KPI de productividad dirigida a Oracle', 'COMPLETED', 'DONE', 'MEDIUM', 1, 4, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Ejemplos KPI productividad', 'Preparar ejemplos con datos recolectados en las primeras 5 semanas', 'COMPLETED', 'DONE', 'MEDIUM', 6, 5, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'KPIs adicionales', 'Definir KPI adicionales (tareas completadas, horas reales, recursos utilizados)', 'COMPLETED', 'DONE', 'MEDIUM', 6, 6, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Ejemplos KPIs adicionales', 'Mostrar ejemplos con datos propios del proyecto', 'COMPLETED', 'DONE', 'MEDIUM', 1, 1, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Costos OCI acumulados', 'Listar servicios OCI utilizados con costos acumulados hasta semana 5', 'COMPLETED', 'DONE', 'MEDIUM', 6, 2, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Proyección costos OCI', 'Proyectar estimación de costos OCI para todo el proyecto', 'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Costo de recursos humanos', 'Calcular costo de recursos humanos en dólares (fórmula: horas × costo/hora)', 'COMPLETED', 'DONE', 'MEDIUM', 1, 4, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Evidencia horas trabajadas', 'Recopilar evidencia de horas trabajadas por cada desarrollador (24 h/sem)', 'COMPLETED', 'DONE', 'MEDIUM', 6, 5, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Diagrama de arquitectura', 'Elaborar diagrama de arquitectura en formato Oracle', 'COMPLETED', 'DONE', 'MEDIUM', 6, 6, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Diagrama modelo relacional', 'Generar diagrama de modelo relacional desde OCI Autonomous Database', 'COMPLETED', 'DONE', 'MEDIUM', 1, 1, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Verificación modelo relacional', 'Verificar que incluya nombres de tablas, atributos, PK y FK (sin ERD ni UML)', 'COMPLETED', 'DONE', 'MEDIUM', 6, 2, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Consultas SQL con tablas anidadas', 'Redactar consultas SQL usando tablas anidadas (semanas 4 y 5)', 'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Evidencia integridad de datos', 'Evidenciar integridad de datos con datos reales del proyecto', 'COMPLETED', 'DONE', 'MEDIUM', 1, 4, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Demo servicio cloud', 'Preparar demostración del servicio cloud implementado', 'COMPLETED', 'DONE', 'MEDIUM', 6, 5, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Backlog en demo', 'Mostrar backlog con tareas en la demo', 'COMPLETED', 'DONE', 'MEDIUM', 6, 6, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Capturas de pantalla ejecución', 'Incluir capturas de pantalla que evidencien la ejecución del servicio', 'COMPLETED', 'DONE', 'MEDIUM', 1, 1, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Gestión del proyecto', 'Documentar gestión del proyecto: Backlog y reportes de equipo', 'COMPLETED', 'DONE', 'MEDIUM', 6, 2, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Plan de calidad', 'Definir plan de calidad: estrategias, procesos y estándares de entrega', 'COMPLETED', 'DONE', 'MEDIUM', 1, 3, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Plan de pruebas', 'Elaborar plan de pruebas: Aceptación, Unitarias e Integración', 'COMPLETED', 'DONE', 'MEDIUM', 1, 4, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 1, 'Matriz de trazabilidad', 'Construir matriz de trazabilidad', 'COMPLETED', 'DONE', 'MEDIUM', 6, 5, DATE '2026-02-25', 1, 1, 'N', NULL, TIMESTAMP '2026-02-11 00:00:00', TIMESTAMP '2026-02-25 00:00:00', 'N');

COMMIT;
