-- ============================================================
-- SPRINT 3
-- ============================================================
INSERT INTO SPRINTS (SPRINT_ID, NAME, START_DATE, END_DATE, STATUS, TOTAL_HOURS, CREATED_AT, IS_DELETED)
VALUES (3, 'Sprint 3 - KPIs, Feature de IA y Video Demo', DATE '2026-04-15', DATE '2026-04-29', 'ACTIVE', 47, TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO PROJECT_SPRINTS (PROJECT_ID, SPRINT_ID, SPRINT_NUMBER, IS_ACTIVE, ASSIGNED_AT)
VALUES (1, 3, 3, 'Y', TIMESTAMP '2026-04-15 00:00:00');

-- ============================================================
-- SPRINT 3 TASKS
-- ============================================================
INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Query SQL KPIs reales', 'Ejecutar query SQL: tasks completadas y horas reales agrupadas por developer y sprint', 'SPRINT', 'PENDING', 'HIGH', 1, 2, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Gráfica de barras KPI', 'Generar gráfica de barras: tasks terminadas por usuario/sprint (herramienta a elección)', 'SPRINT', 'PENDING', 'MEDIUM', 6, 5, DATE '2026-04-29', 3, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Screenshot KPIs en app', 'Tomar screenshot legible de la app con los KPIs visibles (anticipado, no en presentación)', 'SPRINT', 'PENDING', 'MEDIUM', 6, 3, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Slide respaldo KPIs', 'Preparar slide de respaldo con foto/imagen de los KPIs en caso de fallo de conexión OCI', 'SPRINT', 'PENDING', 'LOW', 1, 3, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Verificar datos reales en BD', 'Verificar que todos los datos en la BD sean tareas reales del reto (eliminar datos de prueba)', 'SPRINT', 'PENDING', 'HIGH', 1, 2, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Insertar slide KPIs en video', 'Insertar slide de KPIs al inicio del video demo (ver sección 5)', 'SPRINT', 'PENDING', 'MEDIUM', 6, 5, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Descripción ejecutiva IA', 'Redactar descripción ejecutiva del feature de IA: problema que resuelve y valor de negocio', 'SPRINT', 'PENDING', 'HIGH', 6, 3, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Diapositiva feature IA', 'Diseñar la diapositiva con formato limpio: título, descripción en 3-4 puntos, icono o imagen de apoyo', 'SPRINT', 'PENDING', 'MEDIUM', 6, 5, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Caso de uso IA', 'Identificar el caso de uso principal del feature de IA con datos reales del proyecto', 'SPRINT', 'PENDING', 'HIGH', 1, 3, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Slide INPUT/OUTPUT IA', 'Diseñar la slide con sección INPUT (dato de entrada real) y sección OUTPUT (resultado generado)', 'SPRINT', 'PENDING', 'MEDIUM', 1, 5, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Validar ejemplo IA reproducible', 'Validar que el ejemplo mostrado sea reproducible y corresponda a datos del reto', 'SPRINT', 'PENDING', 'HIGH', 6, 3, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Actualizar diagrama arquitectura', 'Actualizar diagrama de arquitectura Oracle para incluir el componente de IA', 'SPRINT', 'PENDING', 'MEDIUM', 6, 6, DATE '2026-04-29', 3, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Flujo de datos IA en arquitectura', 'Marcar claramente el flujo de datos hacia y desde el feature de IA', 'SPRINT', 'PENDING', 'MEDIUM', 1, 6, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Verificar consistencia arquitectura', 'Verificar consistencia entre el diagrama y la arquitectura real desplegada en OCI', 'SPRINT', 'PENDING', 'MEDIUM', 6, 6, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Grabar segmento KPI video', 'Grabar segmento inicial del video: mostrar gráficas de KPI (tasks completadas y horas reales)', 'SPRINT', 'PENDING', 'HIGH', 6, 5, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Grabar demo feature IA', 'Grabar demo del feature de IA: INPUT real -> procesamiento -> OUTPUT visible', 'SPRINT', 'PENDING', 'HIGH', 1, 3, DATE '2026-04-29', 3, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Editar video final', 'Editar y unir los segmentos en un video final coherente y sin cortes abruptos', 'SPRINT', 'PENDING', 'MEDIUM', 6, 5, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'IP pública visible en video', 'Verificar que la IP pública del servidor sea visible en algún momento del video', 'SPRINT', 'PENDING', 'MEDIUM', 1, 4, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Prueba reproducción video', 'Hacer prueba de reproducción del video completo antes de la presentación', 'SPRINT', 'PENDING', 'MEDIUM', 6, 4, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Documentar dificultades sprint', 'Documentar dificultades actuales del sprint con descripción y causa raíz', 'SPRINT', 'PENDING', 'MEDIUM', 6, 6, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Plan de contingencia', 'Redactar plan de contingencia para cada dificultad identificada', 'SPRINT', 'PENDING', 'MEDIUM', 1, 6, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Plan siguiente sprint', 'Definir plan para el siguiente sprint: objetivos, entregables y responsables', 'SPRINT', 'PENDING', 'MEDIUM', 6, 6, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Estrategia DevOps CI/CD', 'Documentar estrategia DevOps: pipeline CI/CD, herramientas usadas (GitHub Actions, OCI DevOps)', 'SPRINT', 'PENDING', 'HIGH', 1, 6, DATE '2026-04-29', 3, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Diapositiva siguientes pasos', 'Diseñar la diapositiva de siguientes pasos con formato claro y visual', 'SPRINT', 'PENDING', 'LOW', 6, 6, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Verificar página en producción', 'Verificar que la página web esté en producción y la IP pública sea accesible al momento de presentar', 'SPRINT', 'PENDING', 'HIGH', 1, 2, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Confirmar video grabado', 'Confirmar que el video demo esté grabado y listo para reproducirse sin depender de conexión en vivo', 'SPRINT', 'PENDING', 'HIGH', 6, 4, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Auditar BD tareas reales', 'Auditar la BD: eliminar tasks que no sean del reto o capacitaciones Oracle (no clases)', 'SPRINT', 'PENDING', 'HIGH', 1, 2, DATE '2026-04-29', 2, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Verificar horas_reales en KPI', 'Verificar que las horas mostradas en KPI sean horas_reales de la BD (no estimadas ni inventadas)', 'SPRINT', 'PENDING', 'HIGH', 6, 4, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

INSERT INTO TASKS (PROJECT_ID, SPRINT_ID, TITLE, DESCRIPTION, TASK_STAGE, STATUS, PRIORITY, CREATED_BY, ASSIGNED_TO, DUE_DATE, ESTIMATED_HOURS, ACTUAL_HOURS, IS_SUBTASK, PARENT_TASK_ID, CREATED_AT, UPDATED_AT, IS_DELETED)
VALUES (1, 3, 'Confirmar demo inmediata', 'Confirmar que la demo inicie de forma inmediata al comenzar la presentación', 'SPRINT', 'PENDING', 'HIGH', 1, 2, DATE '2026-04-29', 1, NULL, 'N', NULL, TIMESTAMP '2026-04-15 00:00:00', TIMESTAMP '2026-04-15 00:00:00', 'N');

COMMIT;
