/* ============================================================
   KPI SEED DATA — EQUIPO65
   Provides the source-table rows needed to fire all 11 triggers
   and populate KPI_VALUES with realistic initial data.

   Must be run AFTER all 7 initialization steps:
     1. db_schema.sql
     2. template_data/users.sql
     3. template_data/kpis.sql
     4. triggers.sql
     5. template_data/sprints/sprint-1.sql  → TASK_IDs 1–35
     6. template_data/sprints/sprint-2.sql  → TASK_IDs 36–55
     7. template_data/sprints/sprint-3.sql  → TASK_IDs 56–84

   KPIs populated by this file:
     TAREAS_REABIERTAS             (via TASK_STATUS_HISTORY inserts)
     TRAZABILIDAD_TAREAS           (via TASK_STATUS_HISTORY inserts)
     ACTUALIZACION_TAREAS_DIA      (via UPDATE on sprint-3 TASKS)
     DESPLIEGUES_PRODUCCION_SPRINT (via DEPLOYMENTS inserts)
     TASA_EXITO_DESPLIEGUES        (via DEPLOYMENTS inserts)
     MTTR                          (via INCIDENTS inserts + UPDATE)
     DISPONIBILIDAD_SERVICIO       (via INCIDENTS inserts + UPDATE)
     INCIDENTES_SEGURIDAD          (via INCIDENTS inserts)
     INTERACCIONES_BOT             (via BOT_INTERACTIONS inserts)
   ============================================================ */


/* ============================================================
   SECTION 1 — TASK_STATUS_HISTORY
   One IN_PROGRESS→DONE transition per completed task.
   Fires: TRG_KPI_REABIERTAS (skips non-REOPENED)
          TRG_KPI_TRAZABILIDAD (counts tasks still with no history)
   Result: TRAZABILIDAD_TAREAS → 0 for sprints 1 & 2 (all tracked)
           TRAZABILIDAD_TAREAS → 29 for sprint 3 (none started yet)
   ============================================================ */

-- ── Sprint 1 (TASK_IDs 1–35) — closed 2026-02-25 ──────────────
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (1,  'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-02-25 17:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (2,  'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-02-25 17:05:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (3,  'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2026-02-25 17:10:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (4,  'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-02-25 17:15:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (5,  'IN_PROGRESS', 'DONE', 5, TIMESTAMP '2026-02-25 17:20:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (6,  'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-02-25 17:25:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (7,  'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-02-25 17:30:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (8,  'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-02-25 17:35:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (9,  'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2026-02-25 17:40:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (10, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-02-25 17:45:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (11, 'IN_PROGRESS', 'DONE', 5, TIMESTAMP '2026-02-25 17:50:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (12, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-02-25 17:55:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (13, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-02-25 18:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (14, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-02-25 18:05:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (15, 'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2026-02-25 18:10:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (16, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-02-25 18:15:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (17, 'IN_PROGRESS', 'DONE', 5, TIMESTAMP '2026-02-25 18:20:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (18, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-02-25 18:25:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (19, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-02-25 18:30:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (20, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-02-25 18:35:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (21, 'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2026-02-25 18:40:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (22, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-02-25 18:45:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (23, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-02-25 18:50:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (24, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-02-25 18:55:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (25, 'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2026-02-25 19:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (26, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-02-25 19:05:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (27, 'IN_PROGRESS', 'DONE', 5, TIMESTAMP '2026-02-25 19:10:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (28, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-02-25 19:15:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (29, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-02-25 19:20:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (30, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-02-25 19:25:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (31, 'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2026-02-25 19:30:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (32, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-02-25 19:35:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (33, 'IN_PROGRESS', 'DONE', 5, TIMESTAMP '2026-02-25 19:40:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (34, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-02-25 19:45:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (35, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-02-25 19:50:00');

-- ── Sprint 2 (TASK_IDs 36–55) — closed 2026-04-15 ─────────────
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (36, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-04-15 17:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (37, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-04-15 17:10:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (38, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-04-15 17:20:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (39, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-04-15 17:30:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (40, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-04-15 17:40:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (41, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-04-15 17:50:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (42, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-04-15 18:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (43, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-04-15 18:10:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (44, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-04-15 18:20:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (45, 'IN_PROGRESS', 'DONE', 1, TIMESTAMP '2026-04-15 18:30:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (46, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-04-15 18:40:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (47, 'IN_PROGRESS', 'DONE', 2, TIMESTAMP '2026-04-15 18:50:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (48, 'IN_PROGRESS', 'DONE', 4, TIMESTAMP '2026-04-15 19:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (49, 'IN_PROGRESS', 'DONE', 5, TIMESTAMP '2026-04-15 19:10:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (50, 'IN_PROGRESS', 'DONE', 3, TIMESTAMP '2026-04-15 19:20:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (51, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-04-15 19:30:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (52, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-04-15 19:40:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (53, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-04-15 19:50:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (54, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-04-15 20:00:00');
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (55, 'IN_PROGRESS', 'DONE', 6, TIMESTAMP '2026-04-15 20:10:00');

-- ── REOPENED entries (gives TAREAS_REABIERTAS a non-zero value) ─
-- Task 8 (sprint 1): reviewer sent it back once before final approval
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (8,  'DONE',        'REOPENED', 1, TIMESTAMP '2026-02-21 10:00:00');
-- Task 42 (sprint 2): owner validation failed, task was reopened
INSERT INTO TASK_STATUS_HISTORY (TASK_ID, OLD_STATUS, NEW_STATUS, CHANGED_BY, CHANGED_AT) VALUES (42, 'DONE',        'REOPENED', 6, TIMESTAMP '2026-04-10 14:00:00');

COMMIT;


/* ============================================================
   SECTION 2 — TASK UPDATE (sprint 3)
   Touches UPDATED_AT on active sprint tasks so
   TRG_KPI_ACTUALIZACION_DIA fires and records today's activity %.
   All 29 sprint-3 tasks are updated → 100% activity on init day.
   ============================================================ */
UPDATE TASKS SET UPDATED_AT = SYSTIMESTAMP WHERE SPRINT_ID = 3;

COMMIT;


/* ============================================================
   SECTION 3 — DEPLOYMENTS
   Fires: TRG_KPI_DESPLIEGUES_PROD  (PRODUCTION + SUCCESS in active sprint window)
          TRG_KPI_TASA_EXITO         (SUCCESS / total per project)
   ============================================================ */

-- Sprint 1 window (2026-02-11 → 2026-02-25)
INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, '1.0.0', 'STAGING',    'SUCCESS',     TIMESTAMP '2026-02-24 20:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, '1.0.0', 'PRODUCTION', 'SUCCESS',     TIMESTAMP '2026-02-25 22:00:00', NULL);

-- Sprint 2 window (2026-04-01 → 2026-04-15)
INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, '2.0.0', 'STAGING',    'SUCCESS',     TIMESTAMP '2026-04-14 19:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, '2.0.0', 'PRODUCTION', 'FAILED',      TIMESTAMP '2026-04-14 21:00:00', 45);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, '2.1.0', 'PRODUCTION', 'SUCCESS',     TIMESTAMP '2026-04-15 00:30:00', NULL);

-- Sprint 3 window (2026-04-15 → 2026-04-29) — active sprint
INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, '3.0.0', 'QA',         'SUCCESS',     TIMESTAMP '2026-04-22 16:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, '3.0.0', 'STAGING',    'SUCCESS',     TIMESTAMP '2026-04-25 18:00:00', NULL);

INSERT INTO DEPLOYMENTS (PROJECT_ID, VERSION, ENVIRONMENT, STATUS, DEPLOYED_AT, RECOVERY_TIME_MIN)
VALUES (1, '3.0.0', 'PRODUCTION', 'SUCCESS',     TIMESTAMP '2026-04-28 22:00:00', NULL);

COMMIT;


/* ============================================================
   SECTION 4 — INCIDENTS
   INSERT fires: TRG_KPI_INCIDENTES_SEG (TYPE='SECURITY' rows)
                 TRG_KPI_DISPONIBILIDAD  (on insert with no RESOLVED_AT → uptime calc starts)
   UPDATE of RESOLVED_AT fires: TRG_KPI_MTTR, TRG_KPI_DISPONIBILIDAD
   Strategy: insert all rows first, then UPDATE RESOLVED_AT so
             both MTTR and uptime triggers fire with complete data.
   ============================================================ */

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, IS_DELETED)
VALUES (1, 'PERFORMANCE', 'API response times degraded under load during sprint 1 demo', 'HIGH',
        TIMESTAMP '2026-02-23 14:00:00', 'N');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, IS_DELETED)
VALUES (1, 'SECURITY', 'JWT token not expiring correctly — extended session window detected', 'CRITICAL',
        TIMESTAMP '2026-04-08 09:30:00', 'N');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, IS_DELETED)
VALUES (1, 'DEPLOYMENT', 'Sprint 2 first PRODUCTION deploy failed — rollback required', 'HIGH',
        TIMESTAMP '2026-04-14 21:00:00', 'N');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, IS_DELETED)
VALUES (1, 'SECURITY', 'Dependency with known CVE found in pom.xml during sprint 3 review', 'MEDIUM',
        TIMESTAMP '2026-04-20 11:00:00', 'N');

INSERT INTO INCIDENTS (PROJECT_ID, TYPE, DESCRIPTION, SEVERITY, OCCURRED_AT, IS_DELETED)
VALUES (1, 'PERFORMANCE', 'KPI dashboard slow to load when querying all sprints simultaneously', 'LOW',
        TIMESTAMP '2026-04-26 15:00:00', 'N');

-- Resolve the closed incidents — UPDATE fires TRG_KPI_MTTR and TRG_KPI_DISPONIBILIDAD
UPDATE INCIDENTS SET RESOLVED_AT = TIMESTAMP '2026-02-23 16:30:00'
WHERE PROJECT_ID = 1 AND TYPE = 'PERFORMANCE' AND OCCURRED_AT = TIMESTAMP '2026-02-23 14:00:00';

UPDATE INCIDENTS SET RESOLVED_AT = TIMESTAMP '2026-04-08 13:00:00'
WHERE PROJECT_ID = 1 AND TYPE = 'SECURITY' AND OCCURRED_AT = TIMESTAMP '2026-04-08 09:30:00';

UPDATE INCIDENTS SET RESOLVED_AT = TIMESTAMP '2026-04-15 00:30:00'
WHERE PROJECT_ID = 1 AND TYPE = 'DEPLOYMENT' AND OCCURRED_AT = TIMESTAMP '2026-04-14 21:00:00';

COMMIT;


/* ============================================================
   SECTION 5 — BOT_INTERACTIONS
   Fires: TRG_KPI_BOT (counts today's interactions → GLOBAL scope)
   Using SYSTIMESTAMP so the "today" count is always accurate
   on whatever day the script is run.
   ============================================================ */
INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (2, '/start', 'Bienvenido Victor Martinez. Tus tareas activas: 3', SYSTIMESTAMP);

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (3, '/addtask "Setup KPI dashboard" "Implement the KPI chart view" 3 HIGH', 'Tarea creada con ID 85', SYSTIMESTAMP);

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (4, '/assigntask 57', 'Tarea 57 asignada a Miguel Angel Alvarez en Sprint 3', SYSTIMESTAMP);

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (5, '/kpi', 'Sprint 3 — Completadas: 0/29 | Cumplimiento: 0%', SYSTIMESTAMP);

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (1, '/kpi', 'Resumen del proyecto — Total horas reales: 109 | Varianza promedio: 0h', SYSTIMESTAMP);

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (2, '/assigntask 60', 'Tarea 60 asignada a Victor Martinez en Sprint 3', SYSTIMESTAMP);

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (6, '/start', 'Bienvenido Luis Garza Gomez. Tus tareas activas: 5', SYSTIMESTAMP);

INSERT INTO BOT_INTERACTIONS (USER_ID, MESSAGE, RESPONSE, CREATED_AT)
VALUES (3, '/kpi', 'Paolo Gaya — Tareas completadas sprint 2: 3 | Horas reales: 9h', SYSTIMESTAMP);

COMMIT;
